version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-7.1
      - test-5.6
jobs:
  test-7.1: &test-template
    docker:
      - image: circleci/php:7.1
        environment:
          TZ: /usr/share/zoneinfo/Europe/Prague
    steps:
      - checkout
      - run:
          name: Install dependenices
          command: composer install
      - run:
          name: Run tests
          command: composer test

  test-5.6:
    <<: *test-template
    docker:
      - image: circleci/php:5.3
        environment:
          TZ: /usr/share/zoneinfo/Europe/Prague
